#!/bin/bash

read -p "Enter what you want build(UMEM,ROCKSDB): " ENGINE

engine=$(echo $ENGINE | tr '[:upper:]' '[:lower:]') # make ENGINE variable lower case

echo $engine
exit 1
sudo apt-get update -y
sudo apt-get install -y apt-utils 2>&1 | grep -v "debconf: delaying package configuration, since apt-utils is not installed"
sudo apt-get install -y --no-install-recommends cmake git libssl-dev build-essential zlib1g zlib1g-dev python3 python3-dev

git config --global http.sslVerify "false"
git clone https://github.com/unum-cloud/ukv.git && cd ./ukv

cmake -DUKV_BUILD_TESTS=0 -DUKV_BUILD_BENCHMARKS=0 -DUKV_BUILD_ENGINE_${ENGINE}=1 -DUKV_BUILD_API_FLIGHT_CLIENT=0 -DUKV_BUILD_API_FLIGHT_SERVER=1 . && make -j8 ukv_flight_server_${engine}

